### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by zrno** [cinatic/stocks-extension#102]

**Comment by stonedbear** [comment]
almost all extensions are broken cause of this (https://github.com/bmwiedemann/openSUSE/blob/13c1179cab4f21925e453e039e04d9174e286d7a/packages/h/hamster-time-tracker/0174-Fix-compatibility-issues-with-Gnome-shell-46.patch#L4)

There is a fix already in place in this thread for a bitcoin price extension: https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/issues/153 @cinatic - apparently this is easy enough to fix.

ps, thanks for your hard work so far :)

**Comment by Huang-CL** [comment]
The extension hasn't worked for me since I upgraded Ubuntu from 22.04 to 24.04.   I downloaded the release v34 tar.gz and compiled it myself. 

First of all, I'm not sure what is the purpose of [line 75](https://github.com/cinatic/stocks-extension/blob/7944f24f5f48a69b40778576910f39b9c24bf164/Makefile#L75) in Makefile
`rm -rf $(INSTALL_DIR)`

It deletes everything and the `make install` fails because `$(BUILD_DIR)` equals `$(INSTALL_DIR)/_build`. I have to comment the line to compile the package.

After compiling the extension, I can open the settings through the extensions manager, but the ticker doesn't appear in the shell panel, even after I restart the computer.

**Comment by Huang-CL** [comment]
@cinatic 
I have determined that the issue occurs only when using the eastmoney provider, whereas the Yahoo provider is compatible with GNOME 46, as it was in previous versions.

The installation problem I reported earlier was due to a misunderstanding of the installation steps on my part. I initially believed that I needed to download the release package and place it into the directory `~/.local/share/gnome-shell/extensions/stocks@infinicode.de`, followed by executing make install. This approach resulted in deleting the downloaded package. However, I have since learned that if the contents are placed directly into the GNOME path, make install is not required.

To prevent similar confusion, I suggest specifying in the README that the 'Release Package' and 'Make install' methods are two distinct installation options, rather than sequential steps.
